config/routes.rb
Rails.application.routes.draw do
  resources :truetasks
  
  resources :attaches

  resources :old2_attachments
  
  resources :discussions do
    resources :messages
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :projects

  resources :use

  get 'log/login'

  get 'log/signup'

  root "log#index"

end

app/models/attach.rb
class Attach < ApplicationRecord
  has_many_attached :images
end

app/controllers/attaches_controller.rb
class AttachesController < ApplicationController
  before_action :set_attach, only: %i[ show edit update destroy ]

  # GET /attaches or /attaches.json
  def index
    @attaches = Attach.all
  end

  # GET /attaches/1 or /attaches/1.json
  def show
  end

  # GET /attaches/new
  def new
    @attach = Attach.new
  end

  # GET /attaches/1/edit
  def edit
  end

  # POST /attaches or /attaches.json
  def create
    @attach = Attach.new(attach_params)
    #@attach = current_user.attaches.build(attach_params)

    respond_to do |format|
      if @attach.save
        format.html { redirect_to attach_url(@attach), notice: "Attachment was successfully created." }
        format.json { render :show, status: :created, location: @attach }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attaches/1 or /attaches/1.json
  def update
    respond_to do |format|
      if @attach.update(attach_params)
        format.html { redirect_to attach_url(@attach), notice: "Attachment was successfully updated." }
        format.json { render :show, status: :ok, location: @attach }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attaches/1 or /attaches/1.json
  def destroy
    @attach.destroy!

    respond_to do |format|
      format.html { redirect_to attaches_url, notice: "Attachment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attach
      @attach = Attach.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attach_params
      params.require(:attach).permit(images: [])
    end
end

app/helpers/attaches_helper.rb
module AttachesHelper
end

app/views/attaches/_attach.html.erb
<div id="<%= dom_id attach %>">
  <p>
    <strong>File:</strong>
    <%= attach.file %>
  </p>

</div>

<%
=begin %>
<%= image_tag attach.fichier.url(:medium) %>
    <%= link_to "Supprimer", project_attachement_path(@project, attachement), method: :delete %>
<%
=end %>

app/views/attaches/_form.html.erb
<%= form_with(model: attach) do |form| %>
  <% if attach.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(attach.errors.count, "error") %> prohibited this attach from being saved:</h2>

      <ul>
        <% attach.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= form.label :choose_a_file, style: "display: block" %></h5>
    <p class="card-text"><%= form.file_field :images, multiple: true %></p>
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/attaches/edit.html.erb
<h1>Editing attachment</h1>

<%= render "form", attach: @attach %>

<br>

<div>
  <%= link_to "Show this attachment", @attach %> |
  <%= link_to "Back to attachments", attaches_path %>
</div>

app/views/attaches/index.html.erb
<h1>Attachments</h1>

<div id="attaches">
  <% @attaches.each do |attach| %>
    <%= render attach %>
    <p>
      <% attach.images.each do |image| %>
        <%= image_tag image.variant(resize_to_limit: [100, 100]) %>
      <% end %>
    </p>
  <% end %>
</div>

<%= link_to "New attachments", new_attach_path, class: "me-4" %>
<%= link_to "Back to options", discussions_path%>

app/views/attaches/new.html.erb
<h1>New attachment</h1>

<%= render "form", attach: @attach %>

<br>

<div>
  <%= link_to "Back to attachments", attaches_path %>
</div>

app/views/attaches/show.html.erb
<%= render @attach %>

<div>
  <%= link_to "Edit this attachment", edit_attach_path(@attach) %>
  <%= link_to "Back to attachments", attaches_path %>

  <%= button_to "Destroy this attachment", @attach, method: :delete %>
</div>