config/routes.rb
Rails.application.routes.draw do
  resources :truetasks
  
  resources :attaches

  resources :old2_attachments
  
  resources :discussions do
    resources :messages
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :projects

  resources :use

  get 'log/login'

  get 'log/signup'

  root "log#index"

end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: %i[ show edit update destroy ]


  # GET /discussions or /discussions.json
  def index
    @discussions = Discussion.all
  end

  # GET /discussions/1 or /discussions/1.json
  def show
  end

  # GET /discussions/new
  def new
    @discussion = Discussion.new
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions or /discussions.json
  def create
    @discussion = Discussion.new(discussion_params)

    if current_user
      @discussion.user = current_user
      @discussion.save
    else
      redirect_to new_user_session_path
    end

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to discussion_url(@discussion), notice: "Discussion was successfully created." }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1 or /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to discussion_url(@discussion), notice: "Discussion was successfully updated." }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1 or /discussions/1.json
  def destroy
    @discussion.destroy!

    respond_to do |format|
      format.html { redirect_to discussions_url, notice: "Discussion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion
      @discussion = Discussion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def discussion_params
      params.require(:discussion).permit(:nom)
    end
  end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_discussion.html.erb
<div class="card" style="width: 18rem;" id="<%= dom_id discussion %>">
  <div class="card-header">
    <strong><%= discussion.nom %></strong>
    <div class="text-dark">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gear" style="margin-left: 220px ; margin-top: -60px;" viewBox="0 0 16 16">
        <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492zM5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0z"/>
        <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52l-.094-.319zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115l.094-.319z"/>
        <div style="margin-top: -58px; margin-left: 227px;">
          <%=link_to ".",edit_discussion_path(discussion), class: "text-dark fs-5" %>
        </div>
      </svg>
        <div class="border border-gray bg-danger text-center" style="margin-left:230px; width: 30px; height: 30px;">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
      <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
      <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
    </svg>
    <div style="margin-top: -28px">
      <%= link_to ".", discussion_path(discussion), method: :delete, class: "text-danger fs-5" %>
    </div>
  </div>
    </div>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"></li>
  </ul>
  <div class="d-flex justify-content-between">
    <%= link_to "send message", new_discussion_message_path(discussion), class: "text-warning" %>
    <%= link_to "show message", discussion_messages_path(discussion), class: "text-warning" %>
  </div>
</div>

app/views/discussions/_form.html.erb
<%= form_with(model: discussion) do |form| %>
  <% if discussion.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
        <% discussion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nom, style: "display: block" %>
    <%= form.text_field :nom %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<h1>Editing discussion</h1>

<%= render "form", discussion: @discussion %>

<br>

<div>
  <%= link_to "Show this discussion", @discussion %> |
  <%= link_to "Back to discussions", discussions_path %>
</div>

app/views/discussions/index.html.erb
<div class="text-center mb-5 mt-2">
  <h1 class="mb-3">Add all your advanced edittings here</h1>
  <p> Created by: <span class="text-danger"><%=current_user.email%></span></p>
</div>

<div class="flex mt-3">
  <h2 class="fs-5">Members:</h2>
  <p class="mt-2">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen-fill" viewBox="0 0 16 16">
      <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001z"/>
    </svg>
    <%=current_user.email%>
  </p>
</div>
<br>

<div class="my-3">
  <% if current_user.has_role? :admin %>
    <p><%= link_to 'Add new discussion', new_discussion_path %></p>
  <% end %>
  <div class="d-flex justify-content-between">
    <%= render @discussions %>
  </div>
</div>
<hr>
<div class="my-3">
  <p> <%= link_to 'Add new task', new_truetask_path %></p>
  <%= link_to 'all tasks', truetasks_path %>
</div>
<hr>
<div class="my-3">
  <p> <%= link_to 'Add attachments', new_attach_path %></p>
</div>

<div class= "position-absolute end-0 me-3 mt-4 p-2">
  <div>
    <%= link_to "Return" , projects_path, class: "text-warning"%>
  </div>
</div>

<!--
<div id="discussions">
  <% @discussions.each do |discussion| %>
    <%= render discussion %>
    <p>
      <%= link_to "Show this discussion", discussion %>
    </p>
  <% end %>
</div>

<%= link_to "New discussion", new_discussion_path %>
-->

app/views/discussions/new.html.erb
<h1>New discussion</h1>

<%= render "form", discussion: @discussion %>

<br>

<div>
  <%= link_to "Back to discussions", discussions_path %>
</div>

app/views/discussions/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @discussion.nom %></h5>
    <p class="card-text"></p>
    <div class="flex">
      <%= link_to "Edit this discussion", edit_discussion_path(@discussion) %>
      <%= link_to "Back to discussion", discussions_path , class: "mb-1"%>
      <%= button_to "Destroy this discussion", @discussion, method: :delete, class: "bg-danger" %>
    </div>
  </div>
</div>