config/routes.rb
Rails.application.routes.draw do
  resources :truetasks
  
  resources :attaches

  resources :old2_attachments
  
  resources :discussions do
    resources :messages
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :projects

  resources :use

  get 'log/login'

  get 'log/signup'

  root "log#index"

end

app/models/truetask.rb
class Truetask < ApplicationRecord
    validates :done, inclusion: { in: [true, false] }
end

app/controllers/truetasks_controller.rb
class TruetasksController < ApplicationController
  before_action :set_truetask, only: %i[ show edit update destroy ]

  # GET /truetasks or /truetasks.json
  def index
    @truetasks = Truetask.all
  end

  # GET /truetasks/1 or /truetasks/1.json
  def show
  end

  # GET /truetasks/new
  def new
    @truetask = Truetask.new
  end

  # GET /truetasks/1/edit
  def edit
  end

  # POST /truetasks or /truetasks.json
  def create
    @truetask = Truetask.new(truetask_params)


    respond_to do |format|
      if @truetask.save
        format.html { redirect_to truetask_url(@truetask), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @truetask }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @truetask.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /truetasks/1 or /truetasks/1.json
  def update
    respond_to do |format|
      if @truetask.update(truetask_params)
        format.html { redirect_to truetask_url(@truetask), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @truetask }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @truetask.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /truetasks/1 or /truetasks/1.json
  def destroy
    @truetask.destroy!

    respond_to do |format|
      format.html { redirect_to truetasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_truetask
      @truetask = Truetask.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def truetask_params
      params.require(:truetask).permit(:name, :description, :done)
    end
end

app/helpers/truetasks_helper.rb
module TruetasksHelper
end

app/views/truetasks/_form.html.erb
<%= form_with(model: truetask) do |form| %>
  <% if truetask.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(truetask.errors.count, "error") %> prohibited this truetask from being saved:</h2>

      <ul>
        <% truetask.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card text-center">
    <div class="card-header">
      Add new tak
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= form.label :name, style: "display: block" %></h5>
      <p class="card-text"><%= form.text_field :name %></p>
      <h6 class="card-title"><%= form.label :description, style: "display: block" %></h6>
      <p class="card-text"><%= form.text_field :description %></p>
      <p class="card-text"><%= form.check_box :done%> <%= form.label :Task_done_?%></p>
      <%= form.submit%>
    </div>
  </div>
<% end %>

app/views/truetasks/_truetask.html.erb
<div class="card" id="<%= dom_id truetask %>">
  <div class="card-header">
    <%= truetask.name %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= truetask.description %></h5>
    <p class="card-text text-danger">
      <%if truetask.done == true %>
        Done
      <%else%>
        Not Done
      <%end%>
    </p>
  </div>
</div>

app/views/truetasks/edit.html.erb
<h1>Editing Task</h1>

<%= render "form", truetask: @truetask %>

<br>

<div>
  <%= link_to "Show this Task", @truetask %> |
  <%= link_to "Back to Tasks", truetasks_path %>
</div>

app/views/truetasks/index.html.erb
<h1>Tasks</h1>

<div id="truetasks">
  <% @truetasks.each do |truetask| %>
    <%= render truetask %>
    <p>
      <%= link_to "Show this task", truetask %>
    </p>
  <% end %>
</div>

<%= link_to "create New task", new_truetask_path, class: "me-4"%>
<%= link_to "back to options", discussions_path %>

app/views/truetasks/new.html.erb
<%= render "form", truetask: @truetask %>

<br>

<div>
  <%= link_to "Back to tasks", truetasks_path %>
</div>

app/views/truetasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @truetask %>

<div>
  <%= link_to "Edit this Task", edit_truetask_path(@truetask) %> |
  <%= link_to "Back to Tasks", truetasks_path %>

  <%= button_to "Destroy this Task", @truetask, method: :delete %>
</div>